version: '3.8'

services:
  blockchain-lib:
    container_name: "blockchain-lib"
    build:
      dockerfile: "Dockerfile.dev.yml"
      context: .
    volumes:
      - ..:/blockchain-lib:cached
    command: sleep infinity
